import { supabase } from './supabase.js';
import * as XLSX from 'https://cdn.jsdelivr.net/npm/xlsx@0.18.5/+esm';
const eventId=new URLSearchParams(location.search).get('event'),fileInput=document.querySelector('#file'),status=document.querySelector('#importStatus'),preview=document.querySelector('#preview'),importButton=document.querySelector('#importButton'),drawButton=document.querySelector('#drawButton'),winner=document.querySelector('#winner');
let entries=[];
const key=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]/g,'');
function read(row,names){const found=Object.keys(row).find(k=>names.includes(key(k)));return found?String(row[found]??'').trim():''}
const {data:{session}}=await supabase.auth.getSession();if(!session||!eventId)location.href='./';
fileInput.addEventListener('change',async()=>{const file=fileInput.files[0];if(!file)return;status.textContent='Lendo planilha…';try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});entries=rows.map(row=>({name:read(row,['nome','name','participante','cliente']),whatsapp:read(row,['whatsapp','telefone','celular','fone']),instagram:read(row,['instagram','insta']),email:read(row,['email','emailaddress']),raw:row})).filter(x=>x.name);if(!entries.length)throw new Error('A planilha não tem uma coluna de nome reconhecida.');preview.innerHTML=`<p><strong>${entries.length}</strong> registros válidos. Cada um receberá uma chance.</p>`;status.textContent='';importButton.disabled=false}catch(error){status.textContent=error.message||'Não foi possível ler a planilha.';importButton.disabled=true}});
importButton.addEventListener('click',async()=>{importButton.disabled=true;status.textContent='Importando lista…';const {data,error}=await supabase.rpc('roleta_import_list',{p_event_id:eventId,p_entries:entries});if(error){status.textContent='Não foi possível importar a lista.';importButton.disabled=false;return}status.textContent=`${data} registros importados. A lista está pronta.`;drawButton.disabled=false});
drawButton.addEventListener('click',async()=>{if(!confirm('Confirmar o sorteio? O evento será fechado depois do vencedor.'))return;drawButton.disabled=true;status.textContent='Sorteando…';const {data,error}=await supabase.functions.invoke('list-draw',{body:{eventId}});if(error||data?.error){status.textContent='Não foi possível sortear.';drawButton.disabled=false;return}status.textContent='';winner.innerHTML=`<div class="result"><span>✦</span><p class="eyebrow">REGISTRO SORTEADO</p><h2>${data.registration_number}</h2><h3>${data.display_name}</h3><p>O resultado foi registrado e o evento foi fechado.</p></div>`});
