import { supabase } from './supabase.js';
import { SUPABASE_URL } from './config.js';
const slug=new URLSearchParams(location.search).get('evento'),form=document.querySelector('#participantForm'),message=document.querySelector('#formMessage'),screens={form:document.querySelector('#formScreen'),game:document.querySelector('#gameScreen'),result:document.querySelector('#resultScreen')};
const slotGame=document.querySelector('#slotGame'),wheelGame=document.querySelector('#wheelGame'),spinButton=document.querySelector('#spinButton'),wheelButton=document.querySelector('#wheelButton');let participant,layout='slots',spinning=false;
function show(name){Object.entries(screens).forEach(([key,el])=>el.hidden=key!==name)}
async function loadEvent(){if(!slug){message.textContent='Este link de evento não é válido.';return}const {data,error}=await supabase.rpc('roleta_get_public_event',{p_slug:slug});const event=data?.[0];if(error||!event){message.textContent='Este evento não está disponível.';form.querySelector('button').disabled=true;return}layout=event.layout;document.documentElement.style.setProperty('--wine',event.primary_color);document.documentElement.style.setProperty('--gold',event.secondary_color);document.body.style.background=`radial-gradient(circle at 50% 0,${event.secondary_color},${event.primary_color} 44%,#16060c)`;document.querySelector('#gameTitle').textContent=event.title.toUpperCase();slotGame.hidden=layout!=='slots';wheelGame.hidden=layout!=='wheel'}
form.addEventListener('submit',e=>{e.preventDefault();participant=Object.fromEntries(new FormData(form));show('game')});
async function spin(){if(spinning)return;spinning=true;spinButton.disabled=true;wheelButton.disabled=true;document.querySelector('#gameHint').textContent='Girando…';try{const res=await fetch(`${SUPABASE_URL}/functions/v1/spin`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({eventSlug:slug,name:participant.name,whatsapp:participant.whatsapp,instagram:participant.instagram,email:participant.email})});const result=await res.json();if(!res.ok)throw new Error();if(layout==='slots')document.querySelector('.slot-window').classList.add('rolling');else document.querySelector('#wheel').classList.add('rolling');setTimeout(()=>showPrize(result),layout==='slots'?2400:3000)}catch(_){document.querySelector('#gameHint').textContent='Não foi possível girar. Tente novamente.';spinning=false;spinButton.disabled=false;wheelButton.disabled=false}}
function showPrize(result){document.querySelector('#resultSymbol').textContent=result.prize_symbol||'✦';document.querySelector('#resultTitle').textContent=result.prize_title||'Parabéns!';const coupon=document.querySelector('#resultCoupon');coupon.hidden=!result.coupon_code;coupon.textContent=result.coupon_code||'';document.querySelector('#resultText').textContent=result.coupon_code?'Apresente este código à equipe.':'Procure a equipe para receber seu prêmio.';show('result')}
spinButton.addEventListener('click',spin);wheelButton.addEventListener('click',spin);document.querySelector('#newClient').addEventListener('click',()=>location.reload());loadEvent();
